comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

djangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mainsite.feeds import AllPostsRssFeed


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('mainsite.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

mainsite/urls.py
from django.conf.urls import url
from . import views


# namespace
app_name = 'mainsite'
# (?P<pk>[0-9]+)这样的结构是命名捕获

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^cv$', views.CvView.as_view(), name='cv'),
    url(r'^about$', views.AboutView.as_view(), name='about'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# 该装饰器用于兼容python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    # email = models.EmailField(max_length=255)
    # url = models.URLField(blank=True)
    text = models.TextField()
    # 当评论数据加载到数据库时，自动把时间设置为当前时间
    create_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('mainsite.Post')

    def __str__(self):
        return self.text[:20]

mainsite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
import markdown
from django.utils.html import strip_tags


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 摘要
    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User)

    # 阅读量
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    # 待解释：获取post的url， pk是主键
    def get_absolute_url(self):
        return reverse('mainsite:detail', kwargs={'pk': self.pk})

    # 访问量加1，update_fields = ['views']可以提高效率
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 复写save方法，使得如果摘要为空，则自动取body的前50个字符作为摘要
    def save(self, *args, **kwargs):
        if not self.excerpt:
            # 实例化一个Markdown类，渲染body文本
            md = markdown.Markdown(extensions = [
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                ])
            # 将markdown渲染成html文本
            # strip_tags去掉html标签，再截取前50个字符
            self.excerpt = strip_tags(md.convert(self.body))[:50]

        # 调用父类save方法
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']

mainsite/views.py
import markdown
# 用于美化点击目录中标题时的url形式
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

from django.shortcuts import render, get_object_or_404

from .models import Post, Category, Tag
from comments.forms import CommentForm
# 改成类视图
from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView
from django.db.models import Q


# 主页视图
# ListView本身已经传递了分类信息
class IndexView(ListView):
    # 在这个listview里面，用到的模型是Post
    model = Post
    template_name = 'mainsite/index.html'
    # post_list 这个变量名会被传给模板
    context_object_name = 'post_list'
    # 值代表每页有几篇文章
    paginate_by = 3
    
    def get_context_data(self, **kwargs):
        # 在类视图中，需要传递的模版变量字典是通过get_context_data获得的
        # 以下是父类获得的字典，有paginator,page_obj, is_paginated三个变量
        context = super().get_context_data(**kwargs)

        # paginator: Paginator的实例
        # page_obj: Page的实例
        # is_paginated: 是否已经分页
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        
        # pagination_data也是一个字典，里面有我们需要的分页数据
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}

        # 分页算法 直接拷贝自教程

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class PostDetailView(DetailView):
    model = Post
    template_name = 'mainsite/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        # get之后得到self.object，值为Post模型实例
        self.object.increase_views()
        # get均要返回httpresponse
        return response
    
    # get_object和get_context_data在父类get方法的调用中都会被调用
    # 函数再对post的body进行渲染
    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])

        post.body = md.convert(post.body)
        # post可以动态添加toc属性，在model里没有
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


# 显示归档页面，函数的参数列表中使用属性要用双下划线(django要求)
class ArchivesView(ListView):
    model = Post
    template_name = 'mainsite/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year, created_time__month=month)


# 显示分类页面
class CategoryView(ListView):
    model = Post
    template_name = 'mainsite/index.html'
    context_object_name = 'post_list'

    # 复写父类的get_queryset方法，默认获得模型的全部列表数据
    def get_queryset(self):
        # kwargs是从URL捕获的命名组参数值
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# 标签对应的文章页面
class TagView(ListView):
    model = Post
    template_name = 'mainsite/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)

# cv对应页面，暂时为空
class CvView(TemplateView):
    template_name = 'mainsite/cv.html'

# about对应页面
class AboutView(TemplateView):
    template_name = 'mainsite/about.html'

def search(request):
    # 这里的'q'是input的name
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = "请输入关键词"
        return render(request, 'mainsite/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'mainsite/index.html', {'error_msg': error_msg,
                                                   'post_list': post_list})

templates/mainsite/about.html
{% extends 'base.html' %}

{% block main %}


{% endblock main %}

templates/mainsite/cv.html
{% extends 'base.html' %}

{% block main %}


{% endblock main %}

templates/mainsite/detail.html
{% extends 'base.html' %}
{% block main %}
  <article class="post post-{{ post.pk }}">
    <header class="entry-header">
      <h1 class="entry-title">{{ post.title }}</h1>
      <div class="entry-meta">
        <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
        <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
        <span class="post-author"><a href="#">{{ post.author }}</a></span>
        <span class="comments-link"><a href="#comment-district">{{ post.comment_set.count }} 评论</a></span>
        <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
      </div>
    </header>
    <div class="entry-content clearfix">
      {{ post.body|safe }}
      <div class="widget-tag-cloud">
        <ul>
          标签:
          {% for tag in post.tags.all %}
            <li><a href="{% url 'mainsite:tag' tag.pk %}">{{ tag.name }}</a></li>
            {% empty %}
            暂无标签
          {% endfor %}
        </ul>
      </div>
    </div>
  </article>
  <!--
  <section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
      {% csrf_token %}
      <div class="row">-->
        <!-- form.name可以自动渲染成表单控件,而form.name.errors可以渲染表单对应字段的错误-->
        <!--
        <div class="col-md-4">
          <label for="{{ form.name.id_for_label }}">姓名: </label>
          {{ form.name }}
          {{ form.name.errors }}
        </div>

        <div class="col-md-4">
          <label for="{{ form.email.id_for_label }}">邮箱: </label>
          {{ form.email }}
          {{ form.email.errors }}
        </div>
        <div class="col-md-4">
          <label for="{{ form.url.id_for_label }}">个人主页: </label>
          {{ form.url }}
          {{ form.url.errors }}
        </div>-->
          <!--<div class="col-md-4">
            <label for="{{ form.text.id_for_label }}">评论: </label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">发表</button>
          </div> -->
          <!--
        </div>  
      </form>
      <div class="comment-list-panel" id="comment-district">
        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
          {% for comment in comment_list %}
            <li class="comment-item">
              <span class="nickname">{{ comment.name }}</span>
              <time class="submit-date">{{ comment.created_time }}</time>
              <div class="text">
                {{ comment.text }}
              </div>
            </li>
            {% empty %}
            暂无评论
          {% endfor %}
        </ul>
      </div>
    </section> -->
  {% endblock main %}
  {% block toc %}
    <div class="widget widget-content">
      <h3 class="widget-title">文章目录</h3>
      {{ post.toc | safe }}
    </div>
  {% endblock toc %}

templates/mainsite/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <h1 class="entry-title">
            <a href="{{ post.get_absolute_url}}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'mainsite:category' post.category.pk %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
            
        </article>
        {% empty %}
        <div class="no-post">暂无</div>
    {% endfor %}
    <!-- 简单分页效果
    {% if is_paginated %}
        <div class="pagination-simple">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}
            <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    {% endif %} -->
    <!-- 复杂的分页效果 -->
    {% if is_paginated %}
        <div class="pagination">
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <span>...</span>
                {% endif %}
                {% for i in left %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% endif %}
            <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
            {% if right %}
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if right_has_more %}
                    <span>...</span>
                {% endif %}
            {% endif %}
            {% if last %}
                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
        </div>
    {% endif %}
{% endblock main %}