comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

djangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mainsite.feeds import AllPostsRssFeed


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('mainsite.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

mainsite/urls.py
from django.conf.urls import url
from . import views


# namespace
app_name = 'mainsite'
# (?P<pk>[0-9]+)这样的结构是命名捕获

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^cv$', views.CvView.as_view(), name='cv'),
    url(r'^about$', views.AboutView.as_view(), name='about'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>Cloud's Sky</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- css -->
        <!-- 使用CDN来使加载速度更快 -->
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'mainsite/css/pace.css' %}">
        <link rel="stylesheet" href="{% static 'mainsite/css/custom.css' %}">
        <!-- 代码高亮 -->
        <link rel="stylesheet" href="{% static 'mainsite/css/highlights/github.css' %}">
        <!-- js -->
        <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{% static 'mainsite/js/pace.min.js' %}"></script>
        <script src="{% static 'mainsite/js/modernizr.custom.js' %}"></script>
        <style>span.highlighted{color: red;}</style>
    </head>
    <body>
        <div class="container">
            <header id="site-header">
                <div class="row">
                    <div class="col-md-4 col-sm-5 col-xs-8">
                        <div class="logo">
                            <h1><a href="{% url 'mainsite:index' %}">Cloud's Sky</a></h1>
                        </div>
                    </div><!-- col-md-4 -->
                    <div class="col-md-8 col-sm-7 col-xs-4">
                        <nav class="main-nav" role="navigation">
                            <div class="navbar-header">
                                <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                                </button>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-11"><a href="{% url 'mainsite:index' %}" data-hover="home">home</a></li>
                                    <li class="cl-effect-11"><a href="{% url 'mainsite:index' %}" data-hover="blog">blog</a></li>
                                    <li class="cl-effect-11"><a href="{% url 'mainsite:cv' %}" data-hover="cv">cv</a></li>
                                    <li class="cl-effect-11"><a href="{% url 'mainsite:about' %}" data-hover="about">about</a></li>
                                </ul>
                            </div><!-- /.navbar-collapse -->
                        </nav>
                        <div id="header-search-box">
                            <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                            <div id="search-form" class="search-form">
                                <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                                    <input type="search" name="q" placeholder="搜索" required>
                                    <button type="submit"><span class="ion-ios-search-strong"></span></button>
                                </form>
                            </div>
                        </div>
                    </div><!-- col-md-8 -->
                </div><!-- row -->
            </header>
        </div><!-- container-->

        <div class="content-body">
            <div class="container">
                <div class="row">
                    <main class="col-md-8">
                        {% block main %}
                        {% endblock main %}
                    </main>
                    <aside class="col-md-4">
                        {% block toc %}
                        {% endblock toc %}
                        <div class="widget widget-recent-posts">
                            <h3 class="widget-title">最新文章</h3>
                            {% get_recent_posts as recent_post_list %}
                            <ul>
                                {% for post in recent_post_list %}
                                    <li>
                                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    </li>
                                    {% empty %}
                                    暂无文章
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="widget widget-archives">
                            <h3 class="widget-title">归档</h3>
                            {% archives as date_list %}
                            <ul>
                                {% for date in date_list %}
                                    <li>
                                        <a href="{% url 'mainsite:archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                                    </li>
                                    {% empty %}
                                    暂无归档
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="widget widget-category">
                            <h3 class="widget-title">分类</h3>
                            {% get_categories as categories %}
                            <ul>
                                {% for category in categories %}
                                    <li>
                                        <a href="{% url 'mainsite:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
                                    </li>
                                    {% empty %}
                                    暂无分类
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="widget widget-tag-cloud">
                            <h3 class="widget-title">标签云</h3>
                            {% get_tags as tag_list %}
                            <ul>
                                {% for tag in tag_list %}
                                    <li>
                                        <a href="{% url 'mainsite:tag' tag.pk %}">{{ tag.name }}</a>
                                    </li>
                                    {% empty %}
                                    暂无标签
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="rss">
                            <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
        <footer id="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p class="copyright">
                            <a href="http://www.miitbeian.gov.cn">京ICP备17070035号</a>
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Mobile Menu -->
        <div class="overlay overlay-hugeinc">
            <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
            <nav>
                <ul>
                    <li><a href="{% url 'mainsite:index' %}">首页</a></li>
                    <li><a href="full-width.html">博客</a></li>
                    <li><a href="about.html">游戏</a></li>
                    <li><a href="about.html">关于</a></li>
                </ul>
            </nav>
        </div>
        <script src="{% static 'mainsite/js/script.js' %}"></script>
    </body>
</html>